### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by Kabenla** [bramford/ansible-role-docker#1]
Running your ansible Role results in the following error

failed: [host_01] (item=[u'linux-image-extra-4.2.0-34-generic', u'linux-image-extra-virtual']) => {"failed": true, "item": ["linux-image-extra-4.2.0-34-generic", "linux-image-extra-virtual"], "msg": "No package matching 'linux-image-extra-4.2.0-34-generic' is available"}

**Comment by bramford** [comment]
Provide the output of the following commands on the remote _host_01_:
`apt-get update && apt-cache search linux-image`
`uname -a`

**Comment by Kabenla** [comment]
vagrant@localnodeone:~$ sudo apt-get update && apt-cache search linux-image
Hit http://security.ubuntu.com wily-security InRelease
Hit https://apt.dockerproject.org ubuntu-wily InRelease
Hit http://archive.ubuntu.com wily InRelease
Get:1 https://apt.dockerproject.org ubuntu-wily/main amd64 Packages [5,980 B]
Get:2 https://apt.dockerproject.org ubuntu-wily/main Translation-en_US [454 B]
Get:3 https://apt.dockerproject.org ubuntu-wily/main Translation-en [454 B]
Hit http://security.ubuntu.com wily-security/main Sources
Get:4 https://apt.dockerproject.org ubuntu-wily/main Translation-en_US [454 B]
Hit http://archive.ubuntu.com wily-updates InRelease
Get:5 https://apt.dockerproject.org ubuntu-wily/main Translation-en [454 B]
Get:6 https://apt.dockerproject.org ubuntu-wily/main Translation-en_US [454 B]
Hit http://security.ubuntu.com wily-security/restricted Sources
Get:7 https://apt.dockerproject.org ubuntu-wily/main Translation-en [454 B]
Get:8 https://apt.dockerproject.org ubuntu-wily/main Translation-en_US [454 B]
Get:9 https://apt.dockerproject.org ubuntu-wily/main Translation-en [454 B]
Hit http://archive.ubuntu.com wily-backports InRelease
Get:10 https://apt.dockerproject.org ubuntu-wily/main Translation-en_US [454 B]
Ign https://apt.dockerproject.org ubuntu-wily/main Translation-en_US
Get:11 https://apt.dockerproject.org ubuntu-wily/main Translation-en [454 B]
Ign https://apt.dockerproject.org ubuntu-wily/main Translation-en
Hit http://security.ubuntu.com wily-security/universe Sources
Hit http://archive.ubuntu.com wily/main Sources
Hit http://security.ubuntu.com wily-security/multiverse Sources
Hit http://security.ubuntu.com wily-security/main amd64 Packages
Hit http://archive.ubuntu.com wily/restricted Sources
Hit http://security.ubuntu.com wily-security/restricted amd64 Packages
Hit http://archive.ubuntu.com wily/universe Sources
Hit http://security.ubuntu.com wily-security/universe amd64 Packages
Hit http://archive.ubuntu.com wily/multiverse Sources
Hit http://security.ubuntu.com wily-security/multiverse amd64 Packages
Hit http://archive.ubuntu.com wily/main amd64 Packages
Hit http://security.ubuntu.com wily-security/main Translation-en
Hit http://archive.ubuntu.com wily/restricted amd64 Packages
Hit http://security.ubuntu.com wily-security/multiverse Translation-en
Hit http://security.ubuntu.com wily-security/restricted Translation-en
Hit http://archive.ubuntu.com wily/universe amd64 Packages
Hit http://security.ubuntu.com wily-security/universe Translation-en
Hit http://archive.ubuntu.com wily/multiverse amd64 Packages
Hit http://archive.ubuntu.com wily/main Translation-en
Hit http://archive.ubuntu.com wily/multiverse Translation-en
Hit http://archive.ubuntu.com wily/restricted Translation-en
Hit http://archive.ubuntu.com wily/universe Translation-en
Hit http://archive.ubuntu.com wily-updates/main Sources
Hit http://archive.ubuntu.com wily-updates/restricted Sources
Hit http://archive.ubuntu.com wily-updates/universe Sources
Hit http://archive.ubuntu.com wily-updates/multiverse Sources
Hit http://archive.ubuntu.com wily-updates/main amd64 Packages
Hit http://archive.ubuntu.com wily-updates/restricted amd64 Packages
Hit http://archive.ubuntu.com wily-updates/universe amd64 Packages
Hit http://archive.ubuntu.com wily-updates/multiverse amd64 Packages
Hit http://archive.ubuntu.com wily-updates/main Translation-en
Hit http://archive.ubuntu.com wily-updates/multiverse Translation-en
Hit http://archive.ubuntu.com wily-updates/restricted Translation-en
Hit http://archive.ubuntu.com wily-updates/universe Translation-en
Hit http://archive.ubuntu.com wily-backports/main Sources
Hit http://archive.ubuntu.com wily-backports/restricted Sources
Hit http://archive.ubuntu.com wily-backports/universe Sources
Hit http://archive.ubuntu.com wily-backports/multiverse Sources
Hit http://archive.ubuntu.com wily-backports/main amd64 Packages
Hit http://archive.ubuntu.com wily-backports/restricted amd64 Packages
Hit http://archive.ubuntu.com wily-backports/universe amd64 Packages
Hit http://archive.ubuntu.com wily-backports/multiverse amd64 Packages
Hit http://archive.ubuntu.com wily-backports/main Translation-en
Hit http://archive.ubuntu.com wily-backports/multiverse Translation-en
Hit http://archive.ubuntu.com wily-backports/restricted Translation-en
Hit http://archive.ubuntu.com wily-backports/universe Translation-en
Fetched 5,980 B in 7s (790 B/s)
Reading package lists... Done
W: Duplicate sources.list entry https://apt.dockerproject.org/repo/ ubuntu-wily/main amd64 Packages (/var/lib/apt/lists/apt.dockerproject.org_repo_dists_ubuntu-wily_main_binary-amd64_Packages)
W: You may want to run apt-get update to correct these problems
alsa-base - ALSA driver configuration files
linux-image-4.2.0-16-generic - Linux kernel image for version 4.2.0 on 64 bit x86 SMP
linux-image-4.2.0-16-lowlatency - Linux kernel image for version 4.2.0 on 64 bit x86 SMP
linux-image-extra-4.2.0-16-generic - Linux kernel extra modules for version 4.2.0 on 64 bit x86 SMP
linux-image-extra-virtual - Transitional package.
linux-image-generic - Generic Linux kernel image
linux-image-lowlatency - lowlatency Linux kernel image
linux-image-virtual - This package will always depend on the latest minimal generic kernel image.
linux-virtual - Minimal Generic Linux kernel and headers
linux-image-4.2.0-42-generic - Linux kernel image for version 4.2.0 on 64 bit x86 SMP
linux-image-4.2.0-42-lowlatency - Linux kernel image for version 4.2.0 on 64 bit x86 SMP
linux-image-extra-4.2.0-42-generic - Linux kernel extra modules for version 4.2.0 on 64 bit x86 SMP
linux-image-4.2.0-34-generic - Linux kernel image for version 4.2.0 on 64 bit x86 SMP

**Comment by Kabenla** [comment]
vagrant@localnodeone:~$ uname -a
Linux localnodeone 4.2.0-34-generic #39-Ubuntu SMP Thu Mar 10 22:13:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Kabenla** [comment]
The host in question is a VM provided by Virtualbox

**Comment by bramford** [comment]
Your kernel is out-of-date and the matching _extra_ image is no longer provided by your distribution. To fix it, run:
* Run `apt-get install -y linux-image-4.2.0-42-generic && reboot`
* Then re-run the ansible playbook.

This role avoids upgrading the user's linux kernel version for obvious reasons. An option could be to add a variable that performs a kernel upgrade (and defaults to `False`):

`docker_upgrade_kernel: no`

Feel free to implement this and create a pull request.

**Comment by Kabenla** [comment]
Thanks will do

Kabenla
